configmap for certificates
kyma-project/kyma-dashboard pull request #74
Opened 2023-01-13 09:14 UTC by chriskari

**Description**

Changes proposed in this pull request:

- configmap for certificates
- added tests

**Related issue(s)**
https://github.com/kyma-project/busola/issues/1958

2023-01-20 14:18 UTC, Lyczeq requested changes

2023-01-20 14:18 UTC, Lyczeq commented on extensions/configuration/certificates.yaml
> +        version: v1
You're fetching `Secrets` instead of `Issuers`. Please, fix this.

2023-01-20 14:18 UTC, Lyczeq commented on extensions/configuration/certificates.yaml
> +      required: true
Secrets are fetched but they're filtered with a specific condition that is in the `SecretRef.js` file in busola.

```js
  const url = `/api/v1/secrets?labelSelector=${labelSelector ||
    ''}&fieldSelector=${fieldSelector || ''}`;
  const { data: secrets, loading } = useGetList()(url);
  ```
  
In `CertificateCreate.js` file, the component has some props:
```js
      <SecretRef
          advanced
          title={t('certificates.secret-ref')}
          tooltipContent={t('certificates.tooltips.secret-ref')}
          fieldSelector="type=kubernetes.io/tls"
          propertyPath="$.spec.secretRef"
          currentNamespace={namespace}
          required
        />
```  
On of them is fieldSelector which is the condition which Secrets are filtered by.

2023-01-20 14:18 UTC, Lyczeq commented on extensions/configuration/certificates.yaml
> +      required: true
Please, try to add similar condition.

2023-01-20 14:18 UTC, Lyczeq commented on extensions/configuration/certificates.yaml
> +      decodedPlaceholder: spec.certSignReqDecoded
Just as a reminder and information for others and maybe me 😆 , this PR should be merged after this one https://github.com/kyma-project/busola/pull/2288

2023-01-20 14:19 UTC, Lyczeq commented on tests/tests/namespace/test-certificates.spec.js
> +    cy.url().should('match', /certificates$/);
I mean, the `cy.url`

2023-01-25 09:39 UTC, Lyczeq commented
blocked by https://github.com/kyma-project/busola/pull/2308 and https://github.com/kyma-project/busola/pull/2309

2023-01-26 07:19 UTC, Lyczeq commented
/retest

2023-01-27 08:52 UTC, mrCherry97 commented on extensions/configuration/certificates.yaml
> +        - UNKNOWN
one tabulator more

2023-01-27 08:53 UTC, mrCherry97 commented on extensions/configuration/certificates.yaml
> +          - UNKNOWN
one tab more

2023-01-30 08:22 UTC, Lyczeq commented
/retest

2023-01-30 11:38 UTC, Lyczeq approved these changes

2023-01-30 12:23 UTC, merged